name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    # Build dell'applicazione con Maven
    - name: Build with Maven
      run: mvn clean install -DskipTests

# Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build dell'immagine Docker utilizzando il Dockerfile
    - name: Build Docker image
      run: docker build -t antoniocarnevale18/price-art-web-service:latest .

    # Push dell'immagine Docker su Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push antoniocarnevale18/price-art-web-service:latest
